/** @type {import('tailwindcss').Config} */
// "Classic & Trustworthy" library palette (see classic_trustworthy_prompt.md):
// deep navy primary, steel-blue secondary/accent, slate neutrals, emerald
// success, amber warning. Token *names* (M3 roles) are unchanged from the
// previous maroon/gold brand so every component keeps working — only the
// hex values were retinted.
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#93c5fd',
        outline: '#64748b',
        'on-tertiary-fixed': '#064e3b',
        tertiary: '#059669',
        'surface-dim': '#cbd5e1',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#6ee7b7',
        'tertiary-container': '#047857',
        'primary-fixed': '#dbeafe',
        'on-surface-variant': '#475569',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'status-success': '#059669',
        warning: '#d97706',
        'on-warning': '#ffffff',
        'text-secondary': '#475569',
        secondary: '#2563eb',
        background: '#f8fafc',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#a7f3d0',
        'surface-container-highest': '#cbd5e1',
        'secondary-fixed': '#dbeafe',
        'surface-tint': '#1e3a8a',
        surface: '#f8fafc',
        'on-tertiary': '#ffffff',
        'text-primary': '#0f172a',
        'on-surface': '#0f172a',
        'on-background': '#0f172a',
        'on-primary-container': '#dbeafe',
        'on-primary': '#ffffff',
        'outline-variant': '#cbd5e1',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#a7f3d0',
        primary: '#1e3a8a',
        'surface-variant': '#e2e8f0',
        'secondary-container': '#dbeafe',
        'on-secondary-container': '#1e3a8a',
        'secondary-fixed-dim': '#93c5fd',
        'on-error-container': '#93000a',
        'surface-bright': '#f8fafc',
        'inverse-surface': '#1e293b',
        'primary-container': '#1e40af',
        'accent-stats': '#8B5FA3',
        'on-secondary-fixed-variant': '#1d4ed8',
        'surface-container': '#f1f5f9',
        'on-tertiary-fixed-variant': '#047857',
        'inverse-on-surface': '#f1f5f9',
        'on-primary-fixed': '#1e3a8a',
        'surface-container-low': '#f8fafc',
        'on-primary-fixed-variant': '#1d4ed8',
        'primary-fixed-dim': '#93c5fd',
        'surface-container-high': '#e2e8f0',
        'surface-white': '#FFFFFF',
        'on-secondary-fixed': '#1e3a8a',
        'dm-bg': '#0b1220',
        'dm-surface': '#111a2e',
        'dm-surface-alt': '#16213a',
        'dm-border': '#2a3a56',
        'dm-text-secondary': '#b9c4d6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'hero-height': '400px',
        'margin-desktop': '48px',
        base: '8px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'body-lg': ['Noto Sans Thai'],
        'headline-xl-mobile': ['Noto Sans Thai'],
        'headline-xl': ['Noto Sans Thai'],
        'body-md': ['Noto Sans Thai'],
        'label-code': ['IBM Plex Mono'],
        'headline-md': ['Noto Sans Thai'],
        'headline-lg': ['Noto Sans Thai'],
        'label-caps': ['IBM Plex Mono'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl-mobile': ['32px', { lineHeight: '1.2', fontWeight: '800' }],
        'headline-xl': ['48px', { lineHeight: '1.2', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-code': ['14px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
