/** @type {import('tailwindcss').Config} */
// Design tokens copied verbatim from the live tailwind.config block embedded
// in BackEnd/templates/pages/login.html (and every other ported page) — the
// real, already dark-mode-contrast-fixed token set, not the earlier FrontEnd/
// mockup draft in DESIGN.md.
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#ffb2b8',
        outline: '#887273',
        'on-tertiary-fixed': '#002110',
        tertiary: '#00361d',
        'surface-dim': '#d9dadc',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#91d5a8',
        'tertiary-container': '#004f2d',
        'primary-fixed': '#ffdadb',
        'on-surface-variant': '#554243',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'status-success': '#4A7C3F',
        'text-secondary': '#6B7280',
        secondary: '#a53d00',
        background: '#f8f9fb',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#7cc094',
        'surface-container-highest': '#e1e2e4',
        'secondary-fixed': '#ffdbcd',
        'surface-tint': '#9b404d',
        surface: '#f8f9fb',
        'on-tertiary': '#ffffff',
        'text-primary': '#1F2328',
        'on-surface': '#191c1e',
        'on-background': '#191c1e',
        'on-primary-container': '#ff929d',
        'on-primary': '#ffffff',
        'outline-variant': '#dbc0c1',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#acf2c3',
        primary: '#5c101f',
        'surface-variant': '#e1e2e4',
        'secondary-container': '#ff7e44',
        'on-secondary-container': '#682300',
        'secondary-fixed-dim': '#ffb597',
        'on-error-container': '#93000a',
        'surface-bright': '#f8f9fb',
        'inverse-surface': '#2e3132',
        'primary-container': '#7a2734',
        'accent-stats': '#8B5FA3',
        'on-secondary-fixed-variant': '#7e2c00',
        'surface-container': '#edeef0',
        'on-tertiary-fixed-variant': '#05522f',
        'inverse-on-surface': '#f0f1f3',
        'on-primary-fixed': '#40000f',
        'surface-container-low': '#f3f4f6',
        'on-primary-fixed-variant': '#7d2936',
        'primary-fixed-dim': '#ffb2b8',
        'surface-container-high': '#e7e8ea',
        'surface-white': '#FFFFFF',
        'on-secondary-fixed': '#360f00',
        'dm-bg': '#170d0f',
        'dm-surface': '#221317',
        'dm-surface-alt': '#2c1920',
        'dm-border': '#4a2c33',
        'dm-text-secondary': '#d9b3ba',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'hero-height': '400px',
        'margin-desktop': '48px',
        base: '8px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'body-lg': ['Noto Sans Thai'],
        'headline-xl-mobile': ['Noto Sans Thai'],
        'headline-xl': ['Noto Sans Thai'],
        'body-md': ['Noto Sans Thai'],
        'label-code': ['IBM Plex Mono'],
        'headline-md': ['Noto Sans Thai'],
        'headline-lg': ['Noto Sans Thai'],
        'label-caps': ['IBM Plex Mono'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl-mobile': ['32px', { lineHeight: '1.2', fontWeight: '800' }],
        'headline-xl': ['48px', { lineHeight: '1.2', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-code': ['14px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
